package asignaciones;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Alejandro
 */
public class ADCA extends javax.swing.JInternalFrame {

    /**
     * Creates new form ADCA
     */
    public ADCA() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cod_carrera = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cod_sede = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cod_jornada = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cod_seccion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cod_aula = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cod_curso = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        car_alumno = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Label_status = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        nota_asig = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setVisible(true);

        jLabel1.setText("ASIGNACION DE CURSOS A ALUMNOS");

        jLabel2.setText("Código de carrera:");

        jLabel3.setText("Código de sede:");

        jLabel4.setText("Código de jornada:");

        jLabel5.setText("Código de sección:");

        jLabel6.setText("Código de aula:");

        jLabel7.setText("Código de curso:");

        jLabel9.setText("Carnet del alumno:");

        jButton1.setText("ASIGNAR / GUARDAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("BUSCAR ASIGNACION");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Label_status.setText("...");

        jLabel10.setText("Nota asignada");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(car_alumno, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cod_curso, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cod_aula, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cod_seccion, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cod_jornada, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cod_sede, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cod_carrera, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nota_asig))
                .addGap(19, 19, 19))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(Label_status))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jButton1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cod_carrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cod_sede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cod_jornada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cod_seccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cod_aula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cod_curso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(car_alumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(nota_asig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(Label_status)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Codigo que permite insertar registros en al base de datos
        //Diseño del JFrame trabajado por ambos
        try{
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3307/siu", "root", "");
            PreparedStatement pst = cn.prepareStatement("insert into asignacioncursosalumnos values(?,?,?,?,?,?,?,?)");
/*-----------------------------------------------------------------------------------------------------------------------*/
            pst.setString(1, cod_carrera.getText().trim());
            pst.setString(2, cod_sede.getText().trim());
            pst.setString(3, cod_jornada.getText().trim());
            pst.setString(4, cod_seccion.getText().trim());
            pst.setString(5, cod_aula.getText().trim()); 
            pst.setString(6, cod_curso.getText().trim()); 
            pst.setString(7, car_alumno.getText().trim()); 
            pst.setString(8, nota_asig.getText().trim()); 
            pst.executeUpdate();
         //Borra lo que hay en campos
            cod_carrera.setText("");
            cod_sede.setText("");
            cod_jornada.setText("");
            cod_seccion.setText("");
            cod_aula.setText("");
            cod_curso.setText("");
            car_alumno.setText("");
            nota_asig.setText("");
            Label_status.setText("Registro exitoso.");
        }catch (Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //Codigo que permite consultar registros en la base de datos
        try{
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3307/nominabancos", "root", "");
            PreparedStatement pst = cn.prepareStatement("select * from bancobantrab where ID = ?");
/*-----------------------------------------------------------------------------------------------------------------------*/

            //pst.setString(1, txt_buscar.getText().trim());//busca lo que hay en el txt en la base de datos

            ResultSet rs = pst.executeQuery();

            if(rs.next()){
                //Busca lo que está en las " " y lo trae a los txt correspondientes
                cod_carrera.setText(rs.getString("codigo_carrera"));
                cod_sede.setText(rs.getString("codigo_sede"));
                cod_jornada.setText(rs.getString("codigo_jornada"));
                cod_seccion.setText(rs.getString("codigo_seccion"));
                cod_aula.setText(rs.getString("codigo_aula"));
                cod_curso.setText(rs.getString("codigo_curso"));
                car_alumno.setText(rs.getString("carnet_alumno"));
                nota_asig.setText(rs.getString("nota_asignacioncursoalumnos"));
            } else {
                //si el campo no existiera que aparecera un mensaje en el LABEL
                JOptionPane.showMessageDialog(null, "Alumno no registrado.");
            }

        }catch (Exception e){

        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_status;
    private javax.swing.JTextField car_alumno;
    private javax.swing.JTextField cod_aula;
    private javax.swing.JTextField cod_carrera;
    private javax.swing.JTextField cod_curso;
    private javax.swing.JTextField cod_jornada;
    private javax.swing.JTextField cod_seccion;
    private javax.swing.JTextField cod_sede;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nota_asig;
    // End of variables declaration//GEN-END:variables
}
